//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.225
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Xpress.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CommonResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CommonResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Xpress.Resources.CommonResource", typeof(CommonResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        internal static System.Drawing.Bitmap add_16x16 {
            get {
                object obj = ResourceManager.GetObject("add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap add2_16x16 {
            get {
                object obj = ResourceManager.GetObject("add2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_dark_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_dark_green_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_left_triangle_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_left_triangle_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_linked_line_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_linked_line_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_black_16x16 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_black_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_blue_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_blue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_right_triangle_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_right_triangle_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow_unlinked_line_32x32 {
            get {
                object obj = ResourceManager.GetObject("arrow_unlinked_line_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow2_right_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("arrow2_right_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow2_right_red_16x16_short {
            get {
                object obj = ResourceManager.GetObject("arrow2_right_red_16x16_short", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap arrow2_right_red_24x24 {
            get {
                object obj = ResourceManager.GetObject("arrow2_right_red_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap blank {
            get {
                object obj = ResourceManager.GetObject("blank", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_software_32x32 {
            get {
                object obj = ResourceManager.GetObject("box_software_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap box_software_32x321 {
            get {
                object obj = ResourceManager.GetObject("box_software_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_32x32 {
            get {
                object obj = ResourceManager.GetObject("branch_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("branch_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("branch_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap branch_find_32x32 {
            get {
                object obj = ResourceManager.GetObject("branch_find_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_ball_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_green_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_ball_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_ball_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_green_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_green_red_32x32 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_green_red_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_red_32x32 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_red_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_yellow_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_yellow_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_square_yellow_24x24 {
            get {
                object obj = ResourceManager.GetObject("bullet_square_yellow_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_green_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_green_24x24 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_green_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_green_left_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_green_left_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_green_left_24x24 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_green_left_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_green_short_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_green_short_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_red_24x24 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_red_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap bullet_triangle_red_left_16x16 {
            get {
                object obj = ResourceManager.GetObject("bullet_triangle_red_left_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap businessman2_16x16 {
            get {
                object obj = ResourceManager.GetObject("businessman2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap businessman2_24x24 {
            get {
                object obj = ResourceManager.GetObject("businessman2_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculate {
            get {
                object obj = ResourceManager.GetObject("calculate", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_24x24 {
            get {
                object obj = ResourceManager.GetObject("calculator_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_32x32 {
            get {
                object obj = ResourceManager.GetObject("calculator_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_32x321 {
            get {
                object obj = ResourceManager.GetObject("calculator_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap calculator_update_rules_32x32 {
            get {
                object obj = ResourceManager.GetObject("calculator_update_rules_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera2_16x16 {
            get {
                object obj = ResourceManager.GetObject("camera2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera2_24x24 {
            get {
                object obj = ResourceManager.GetObject("camera2_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera2_32x32 {
            get {
                object obj = ResourceManager.GetObject("camera2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap camera2_32x321 {
            get {
                object obj = ResourceManager.GetObject("camera2_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cancel {
            get {
                object obj = ResourceManager.GetObject("cancel", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap CANCEL_RED_16x16 {
            get {
                object obj = ResourceManager.GetObject("CANCEL_RED_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap check_16x16 {
            get {
                object obj = ResourceManager.GetObject("check_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap circle_green_red_16x16_B {
            get {
                object obj = ResourceManager.GetObject("circle_green_red_16x16_B", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_history_32x32 {
            get {
                object obj = ResourceManager.GetObject("clock_history_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap clock_history_32x321 {
            get {
                object obj = ResourceManager.GetObject("clock_history_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap compass_32x32 {
            get {
                object obj = ResourceManager.GetObject("compass_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contract_32x32 {
            get {
                object obj = ResourceManager.GetObject("contract_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap contract_32x321 {
            get {
                object obj = ResourceManager.GetObject("contract_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy {
            get {
                object obj = ResourceManager.GetObject("copy", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_16x16 {
            get {
                object obj = ResourceManager.GetObject("copy_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_24x24 {
            get {
                object obj = ResourceManager.GetObject("copy_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap copy_32x32 {
            get {
                object obj = ResourceManager.GetObject("copy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cubes_yellow_32x32 {
            get {
                object obj = ResourceManager.GetObject("cubes_yellow_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cubes_yellow_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("cubes_yellow_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut {
            get {
                object obj = ResourceManager.GetObject("cut", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_16x16 {
            get {
                object obj = ResourceManager.GetObject("cut_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_24x24 {
            get {
                object obj = ResourceManager.GetObject("cut_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap cut_32x32 {
            get {
                object obj = ResourceManager.GetObject("cut_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap dataGridViewImageColumn1_Image {
            get {
                object obj = ResourceManager.GetObject("dataGridViewImageColumn1_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_time_preferences_32x32 {
            get {
                object obj = ResourceManager.GetObject("date_time_preferences_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap date_time_preferences_32x321 {
            get {
                object obj = ResourceManager.GetObject("date_time_preferences_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_16x16 {
            get {
                object obj = ResourceManager.GetObject("delete_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_24x24 {
            get {
                object obj = ResourceManager.GetObject("delete_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_activated_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_activated_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_activation_pending_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_activation_pending_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_business_person_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_business_person_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_business_person2_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_business_person2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_chart_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_chart_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_chart_32x321 {
            get {
                object obj = ResourceManager.GetObject("document_chart_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_chart2_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_chart2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_deactivated_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_deactivated_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_deactivation_pending_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_deactivation_pending_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_delete_32x321 {
            get {
                object obj = ResourceManager.GetObject("document_delete_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_edit_plain_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_edit_plain_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_gear2_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_gear2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_import_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_import_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_into_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_into_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_into_32x321 {
            get {
                object obj = ResourceManager.GetObject("document_into_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_into_cancel_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_into_cancel_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_into_cancel2_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_into_cancel2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_ok_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_ok_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_out_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_out_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_out_32x321 {
            get {
                object obj = ResourceManager.GetObject("document_out_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_16x16 {
            get {
                object obj = ResourceManager.GetObject("document_plain_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_plain_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_plain_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_add_16x16 {
            get {
                object obj = ResourceManager.GetObject("document_plain_add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_add_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_plain_add_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_plain_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_plain_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_red_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_plain_red_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_plain_solid_green_box_16x16 {
            get {
                object obj = ResourceManager.GetObject("document_plain_solid_green_box_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reservation_cancel_pending_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_reservation_cancel_pending_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reservation_cancel_pending_24x24_alt {
            get {
                object obj = ResourceManager.GetObject("document_reservation_cancel_pending_24x24_alt", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reservation_pending_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_reservation_pending_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reservation_release_pending_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_reservation_release_pending_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reserved_by_other_user_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_reserved_by_other_user_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_reserved_by_user_24x24 {
            get {
                object obj = ResourceManager.GetObject("document_reserved_by_user_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_update_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_update_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_view_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_view_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_zoom_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_zoom_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_zoom_in_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_zoom_in_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_zoom_none_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_zoom_none_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap document_zoom_out_32x32 {
            get {
                object obj = ResourceManager.GetObject("document_zoom_out_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_16x16 {
            get {
                object obj = ResourceManager.GetObject("documents_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_add_16x16 {
            get {
                object obj = ResourceManager.GetObject("documents_add_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_add_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_add_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_edit_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_edit_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_exchange_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_exchange_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_gear_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_gear_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_import_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_import_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_recent_green_arrow_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_recent_green_arrow_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_recent_red_arrow_24x24 {
            get {
                object obj = ResourceManager.GetObject("documents_recent_red_arrow_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap documents_reports_32x32 {
            get {
                object obj = ResourceManager.GetObject("documents_reports_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_16x16 {
            get {
                object obj = ResourceManager.GetObject("error_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap error_24x24 {
            get {
                object obj = ResourceManager.GetObject("error_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floppy_disk_16x16 {
            get {
                object obj = ResourceManager.GetObject("floppy_disk_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floppy_disk_24x24 {
            get {
                object obj = ResourceManager.GetObject("floppy_disk_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floppy_disk_32x32 {
            get {
                object obj = ResourceManager.GetObject("floppy_disk_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap floppy_disk_edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("floppy_disk_edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_24x24 {
            get {
                object obj = ResourceManager.GetObject("folder_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_document_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_document_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_document_24x24 {
            get {
                object obj = ResourceManager.GetObject("folder_document_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_document_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_document_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_document2_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_document2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_edit_16x16_A {
            get {
                object obj = ResourceManager.GetObject("folder_edit_16x16_A", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_gear_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_gear_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_lock_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_lock_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_ok_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_ok_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_reversed_16x16 {
            get {
                object obj = ResourceManager.GetObject("folder_reversed_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_reversed_24x24 {
            get {
                object obj = ResourceManager.GetObject("folder_reversed_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folder_view_32x32 {
            get {
                object obj = ResourceManager.GetObject("folder_view_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap folders_32x32 {
            get {
                object obj = ResourceManager.GetObject("folders_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_blue_edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("form_blue_edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_green_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("form_green_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_red_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("form_red_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap form_yellow_export_32x32 {
            get {
                object obj = ResourceManager.GetObject("form_yellow_export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("funnel_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap funnel_delete_32x321 {
            get {
                object obj = ResourceManager.GetObject("funnel_delete_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap go_to_workbook_16x16 {
            get {
                object obj = ResourceManager.GetObject("go_to_workbook_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_any_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_any_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_exclude_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_exclude_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_group_subgroup_copy_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_group_subgroup_copy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_group_subgroup_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_group_subgroup_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_plain_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_plain_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_project_copy_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_project_copy_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap grouping_project_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("grouping_project_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap handcart {
            get {
                object obj = ResourceManager.GetObject("handcart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap hands {
            get {
                object obj = ResourceManager.GetObject("hands", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help {
            get {
                object obj = ResourceManager.GetObject("help", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help_16x16 {
            get {
                object obj = ResourceManager.GetObject("help_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help2_16x16 {
            get {
                object obj = ResourceManager.GetObject("help2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap help2_24x24 {
            get {
                object obj = ResourceManager.GetObject("help2_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap house {
            get {
                object obj = ResourceManager.GetObject("house", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap import_32x32 {
            get {
                object obj = ResourceManager.GetObject("import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index_32x32 {
            get {
                object obj = ResourceManager.GetObject("index_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("index_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index_replace_32x32 {
            get {
                object obj = ResourceManager.GetObject("index_replace_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap index_up_32x32 {
            get {
                object obj = ResourceManager.GetObject("index_up_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap information_24x24 {
            get {
                object obj = ResourceManager.GetObject("information_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_dollar_32x32 {
            get {
                object obj = ResourceManager.GetObject("invoice_dollar_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap invoice_dollar_32x321 {
            get {
                object obj = ResourceManager.GetObject("invoice_dollar_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Left {
            get {
                object obj = ResourceManager.GetObject("Left", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap letter {
            get {
                object obj = ResourceManager.GetObject("letter", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link_32x32 {
            get {
                object obj = ResourceManager.GetObject("link_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link_edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("link_edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link_export1_32x32 {
            get {
                object obj = ResourceManager.GetObject("link_export1_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link_export2_32x32 {
            get {
                object obj = ResourceManager.GetObject("link_export2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap link_new_32x32 {
            get {
                object obj = ResourceManager.GetObject("link_new_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap lock_24x24 {
            get {
                object obj = ResourceManager.GetObject("lock_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap man {
            get {
                object obj = ResourceManager.GetObject("man", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marker_32x32 {
            get {
                object obj = ResourceManager.GetObject("marker_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap marker_32x321 {
            get {
                object obj = ResourceManager.GetObject("marker_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_bill_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_bill_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_bill_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_bill_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_bills_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_bills_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_envelope_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_envelope_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_envelope_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_envelope_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_envelope_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_envelope_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_envelope_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_envelope_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money_refund_32x32 {
            get {
                object obj = ResourceManager.GetObject("money_refund_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap money2_edit_32x32 {
            get {
                object obj = ResourceManager.GetObject("money2_edit_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap moneybag2_32x32 {
            get {
                object obj = ResourceManager.GetObject("moneybag2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor_preferences_32x32 {
            get {
                object obj = ResourceManager.GetObject("monitor_preferences_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap monitor_preferences_32x321 {
            get {
                object obj = ResourceManager.GetObject("monitor_preferences_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_blue_16X16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_blue_16X16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_gray_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_gray_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_green_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_green_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_light_blue_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_light_blue_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_white_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_white_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_plain_yellow_16x16 {
            get {
                object obj = ResourceManager.GetObject("nav_plain_yellow_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_refresh_green_32x32 {
            get {
                object obj = ResourceManager.GetObject("nav_refresh_green_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap nav_refresh_green_32x321 {
            get {
                object obj = ResourceManager.GetObject("nav_refresh_green_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_plus_16x16 {
            get {
                object obj = ResourceManager.GetObject("navigate_plus_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap navigate_plus_24x24 {
            get {
                object obj = ResourceManager.GetObject("navigate_plus_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newDeal {
            get {
                object obj = ResourceManager.GetObject("newDeal", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap newScenario {
            get {
                object obj = ResourceManager.GetObject("newScenario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap ok_16x16 {
            get {
                object obj = ResourceManager.GetObject("ok_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OpenScenario {
            get {
                object obj = ResourceManager.GetObject("OpenScenario", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPTIMUM_16x16 {
            get {
                object obj = ResourceManager.GetObject("OPTIMUM_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap optimum_24x24 {
            get {
                object obj = ResourceManager.GetObject("optimum_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap OPTIMUM_32x32 {
            get {
                object obj = ResourceManager.GetObject("OPTIMUM_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste {
            get {
                object obj = ResourceManager.GetObject("paste", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_16x16 {
            get {
                object obj = ResourceManager.GetObject("paste_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_24x24 {
            get {
                object obj = ResourceManager.GetObject("paste_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap paste_32x32 {
            get {
                object obj = ResourceManager.GetObject("paste_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pencil_16x16 {
            get {
                object obj = ResourceManager.GetObject("pencil_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictureBox71_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox71_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictureBox75_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox75_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap pictureBox76_Image {
            get {
                object obj = ResourceManager.GetObject("pictureBox76_Image", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap preferences_24x24 {
            get {
                object obj = ResourceManager.GetObject("preferences_24x24", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap presentation_chart_32x32 {
            get {
                object obj = ResourceManager.GetObject("presentation_chart_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap presentation_chart_32x321 {
            get {
                object obj = ResourceManager.GetObject("presentation_chart_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printer2_32x32 {
            get {
                object obj = ResourceManager.GetObject("printer2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap printer2_32x321 {
            get {
                object obj = ResourceManager.GetObject("printer2_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Right {
            get {
                object obj = ResourceManager.GetObject("Right", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap save {
            get {
                object obj = ResourceManager.GetObject("save", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap scroll_32x32 {
            get {
                object obj = ResourceManager.GetObject("scroll_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("server_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap server_add_32x321 {
            get {
                object obj = ResourceManager.GetObject("server_add_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopping_basket_32x32 {
            get {
                object obj = ResourceManager.GetObject("shopping_basket_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap shopping_basket_32x321 {
            get {
                object obj = ResourceManager.GetObject("shopping_basket_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sign_forbidden_16x16 {
            get {
                object obj = ResourceManager.GetObject("sign_forbidden_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap sperator {
            get {
                object obj = ResourceManager.GetObject("sperator", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap square_green_red_16x16 {
            get {
                object obj = ResourceManager.GetObject("square_green_red_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap star {
            get {
                object obj = ResourceManager.GetObject("star", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_current_16x16 {
            get {
                object obj = ResourceManager.GetObject("status_current_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_deleted_16x16 {
            get {
                object obj = ResourceManager.GetObject("status_deleted_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_edited_16x16 {
            get {
                object obj = ResourceManager.GetObject("status_edited_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap status_new_16x16 {
            get {
                object obj = ResourceManager.GetObject("status_new_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_percent_32x32 {
            get {
                object obj = ResourceManager.GetObject("symbol_percent_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_percent_32x321 {
            get {
                object obj = ResourceManager.GetObject("symbol_percent_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap symbol_questionmark_16x16 {
            get {
                object obj = ResourceManager.GetObject("symbol_questionmark_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Sync {
            get {
                object obj = ResourceManager.GetObject("Sync", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_column_preferences_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_column_preferences_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_column_preferences_32x321 {
            get {
                object obj = ResourceManager.GetObject("table_column_preferences_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_connection_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_connection_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_connection_32x321 {
            get {
                object obj = ResourceManager.GetObject("table_connection_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_row_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_row_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_add_32x321 {
            get {
                object obj = ResourceManager.GetObject("table_row_add_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_row_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_delete_32x321 {
            get {
                object obj = ResourceManager.GetObject("table_row_delete_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table_row_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("table_row_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_16x16 {
            get {
                object obj = ResourceManager.GetObject("table2_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_check_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_check_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_export_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_export_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_light_blue_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_light_blue_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_light_blue_export_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_light_blue_export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_light_blue_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_light_blue_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_orange_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_orange_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_orange_export_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_orange_export_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_all_orange_import_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_all_orange_import_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_block_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_block_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_block_32x321 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_block_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_selection_column_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_selection_column_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap table2_stop_32x32 {
            get {
                object obj = ResourceManager.GetObject("table2_stop_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tables_row_32x32 {
            get {
                object obj = ResourceManager.GetObject("tables_row_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap tables_row_32x321 {
            get {
                object obj = ResourceManager.GetObject("tables_row_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap target3_32x32 {
            get {
                object obj = ResourceManager.GetObject("target3_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_list_bullets_32x32 {
            get {
                object obj = ResourceManager.GetObject("text_list_bullets_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap text_list_bullets_32x321 {
            get {
                object obj = ResourceManager.GetObject("text_list_bullets_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_32x32 {
            get {
                object obj = ResourceManager.GetObject("toolbox_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap toolbox_32x321 {
            get {
                object obj = ResourceManager.GetObject("toolbox_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap touch_16x16 {
            get {
                object obj = ResourceManager.GetObject("touch_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap transparent_32x32 {
            get {
                object obj = ResourceManager.GetObject("transparent_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap unknown_16x16 {
            get {
                object obj = ResourceManager.GetObject("unknown_16x16", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_monitor_32x32 {
            get {
                object obj = ResourceManager.GetObject("user_monitor_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap user_monitor_32x321 {
            get {
                object obj = ResourceManager.GetObject("user_monitor_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users4_32x32 {
            get {
                object obj = ResourceManager.GetObject("users4_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap users4_32x321 {
            get {
                object obj = ResourceManager.GetObject("users4_32x321", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_add_32x32 {
            get {
                object obj = ResourceManager.GetObject("view_add_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap view_delete_32x32 {
            get {
                object obj = ResourceManager.GetObject("view_delete_32x32", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
